# Form implementation generated from reading ui file 'timer_control.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimerControl(object):
    def setupUi(self, TimerControl):
        TimerControl.setObjectName("TimerControl")
        TimerControl.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        TimerControl.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimerControl)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_label = QtWidgets.QLabel(parent=TimerControl)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.verticalLayout.addWidget(self.time_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(parent=TimerControl)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.pause_btn = QtWidgets.QPushButton(parent=TimerControl)
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(parent=TimerControl)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TimerControl)
        QtCore.QMetaObject.connectSlotsByName(TimerControl)

    def retranslateUi(self, TimerControl):
        _translate = QtCore.QCoreApplication.translate
        TimerControl.setWindowTitle(_translate("TimerControl", "Form"))
        self.time_label.setText(_translate("TimerControl", "00:00:00"))
        self.start_btn.setText(_translate("TimerControl", "Старт"))
        self.pause_btn.setText(_translate("TimerControl", "Пауза"))
        self.stop_btn.setText(_translate("TimerControl", "Стоп"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimerControl = QtWidgets.QWidget()
    ui = Ui_TimerControl()
    ui.setupUi(TimerControl)
    TimerControl.show()
    sys.exit(app.exec())
