# Form implementation generated from reading ui file 'last_image.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_last_image(object):
    def setupUi(self, last_image):
        last_image.setObjectName("last_image")
        last_image.resize(368, 281)
        self.horizontalLayout = QtWidgets.QHBoxLayout(last_image)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.last_image_label = QtWidgets.QLabel(parent=last_image)
        self.last_image_label.setText("")
        self.last_image_label.setObjectName("last_image_label")
        self.horizontalLayout.addWidget(self.last_image_label)

        self.retranslateUi(last_image)
        QtCore.QMetaObject.connectSlotsByName(last_image)

    def retranslateUi(self, last_image):
        _translate = QtCore.QCoreApplication.translate
        last_image.setWindowTitle(_translate("last_image", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    last_image = QtWidgets.QWidget()
    ui = Ui_last_image()
    ui.setupUi(last_image)
    last_image.show()
    sys.exit(app.exec())
