# Form implementation generated from reading ui file 'temperature_control.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_temperature_control(object):
    def setupUi(self, temperature_control):
        temperature_control.setObjectName("temperature_control")
        temperature_control.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        temperature_control.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(temperature_control)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.send_widget = QtWidgets.QWidget(parent=temperature_control)
        self.send_widget.setObjectName("send_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.send_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.send_layout = QtWidgets.QFormLayout()
        self.send_layout.setObjectName("send_layout")
        self.send_address_label = QtWidgets.QLabel(parent=self.send_widget)
        self.send_address_label.setObjectName("send_address_label")
        self.send_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.send_address_label)
        self.send_address_spinbox = QtWidgets.QSpinBox(parent=self.send_widget)
        self.send_address_spinbox.setMaximum(9999)
        self.send_address_spinbox.setObjectName("send_address_spinbox")
        self.send_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.send_address_spinbox)
        self.function_type_label = QtWidgets.QLabel(parent=self.send_widget)
        self.function_type_label.setObjectName("function_type_label")
        self.send_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.function_type_label)
        self.function_type_combo = QtWidgets.QComboBox(parent=self.send_widget)
        self.function_type_combo.setObjectName("function_type_combo")
        self.send_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.function_type_combo)
        self.send_value_label = QtWidgets.QLabel(parent=self.send_widget)
        self.send_value_label.setObjectName("send_value_label")
        self.send_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.send_value_label)
        self.values_field = QtWidgets.QLineEdit(parent=self.send_widget)
        self.values_field.setObjectName("values_field")
        self.send_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.values_field)
        self.verticalLayout_2.addLayout(self.send_layout)
        self.send_btn = QtWidgets.QPushButton(parent=self.send_widget)
        self.send_btn.setObjectName("send_btn")
        self.verticalLayout_2.addWidget(self.send_btn)
        self.horizontalLayout.addWidget(self.send_widget)
        self.recieve_widget = QtWidgets.QWidget(parent=temperature_control)
        self.recieve_widget.setObjectName("recieve_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.recieve_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.recieve_layout = QtWidgets.QFormLayout()
        self.recieve_layout.setObjectName("recieve_layout")
        self.recieve_address_label = QtWidgets.QLabel(parent=self.recieve_widget)
        self.recieve_address_label.setObjectName("recieve_address_label")
        self.recieve_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.recieve_address_label)
        self.recieve_address_spinbox = QtWidgets.QSpinBox(parent=self.recieve_widget)
        self.recieve_address_spinbox.setMaximum(15000)
        self.recieve_address_spinbox.setObjectName("recieve_address_spinbox")
        self.recieve_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.recieve_address_spinbox)
        self.recieve_value_label = QtWidgets.QLabel(parent=self.recieve_widget)
        self.recieve_value_label.setObjectName("recieve_value_label")
        self.recieve_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.recieve_value_label)
        self.recieve_value_lcd = QtWidgets.QLCDNumber(parent=self.recieve_widget)
        self.recieve_value_lcd.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.recieve_value_lcd.setObjectName("recieve_value_lcd")
        self.recieve_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.recieve_value_lcd)
        self.verticalLayout.addLayout(self.recieve_layout)
        self.read_btn = QtWidgets.QPushButton(parent=self.recieve_widget)
        self.read_btn.setObjectName("read_btn")
        self.verticalLayout.addWidget(self.read_btn)
        self.horizontalLayout.addWidget(self.recieve_widget)

        self.retranslateUi(temperature_control)
        QtCore.QMetaObject.connectSlotsByName(temperature_control)

    def retranslateUi(self, temperature_control):
        _translate = QtCore.QCoreApplication.translate
        temperature_control.setWindowTitle(_translate("temperature_control", "Form"))
        self.send_address_label.setText(_translate("temperature_control", "Адрес"))
        self.function_type_label.setText(_translate("temperature_control", "Функция"))
        self.send_value_label.setText(_translate("temperature_control", "Значение(я)"))
        self.send_btn.setText(_translate("temperature_control", "Отправить"))
        self.recieve_address_label.setText(_translate("temperature_control", "Адрес"))
        self.recieve_value_label.setText(_translate("temperature_control", "Значение"))
        self.read_btn.setText(_translate("temperature_control", "Считать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    temperature_control = QtWidgets.QWidget()
    ui = Ui_temperature_control()
    ui.setupUi(temperature_control)
    temperature_control.show()
    sys.exit(app.exec())
